name: Scheduled Build Check

on:
  schedule:
    #        ┌─ minute
    #        │ ┌─ hour (UTC)
    #        │ │ ┌─ day of month
    #        │ │ │    ┌─ month
    #        │ │ │    │ ┌─ day of week
    - cron: '0 8 1,15 * *'

permissions:
  contents: read

jobs:
  build:
    name: scheduled build check 🕐
    if: vars.IS_TEMPLATE_REPO == 'true'
    uses: ./.github/workflows/build.yaml
