name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

env:
  OUT_DIR: output
  PDF_NAME: monografia.pdf

jobs:
  build:
    name: build 🛠️
    runs-on: ubuntu-latest
    container: texlive/texlive:latest
    concurrency:
      group: build-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: 🛎️ Checkout code
        uses: actions/checkout@v6
      - name: 📜 Make PDF
        run: make
      - name: 📤 Upload PDF artifact
        uses: actions/upload-artifact@v7
        with:
          name: monografia
          path: ${{ env.OUT_DIR }}/${{ env.PDF_NAME }}

  deploy:
    name: deploy 🚀
    needs: [build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    concurrency:
      group: pdf-deploy
      cancel-in-progress: false
    permissions:
      contents: write
    steps:
      - name: 🛎️ Checkout code
        uses: actions/checkout@v6
      - name: 📥 Upload PDF artifact
        uses: actions/download-artifact@v8
        with:
          name: monografia
      - name: 📂 Move PDF to output directory
        run: |
          mkdir -p ${{ env.OUT_DIR }}
          mv ${{ env.PDF_NAME }} ${{ env.OUT_DIR }}
      - name: 🚀 Upload PDF to orphan branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ${{ env.OUT_DIR }}
          branch: pdf
