name: PR

on:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: checks ✅
    uses: ./.github/workflows/build.yaml
    concurrency:
      group: build-${{ github.ref }}
      cancel-in-progress: true
